EXPERIMENT_NAME: 4g_classification
AZURE_CLIENT_ID: 9220bb71-8bbd-4aa9-a07b-ff287ab39f35
AZURE_TENANT_ID: 608bf83f-6d9a-4888-ad38-d95f1528c410
AZURE_CLIENT_SECRET: CZX8Q~lkcwdVpXYq9o2YTgLMSIb.eCcNm4Ds~dno
SUBSCRIPTION_ID: 33579ab2-7df4-4870-ada1-4db803eff7ad
RESOURCE_GROUP: NM_Analytics
WORKSPACE: nm_analytics_poc_ml
ENDPOINT_NAME: 4g_classification
OPTIMIZATION_METRIC: accuracy