# Conda environment specification. The dependencies defined in this file will
# be automatically provisioned for managed runs. These include runs against
# the localdocker, remotedocker, and cluster compute targets.

name: 4g_classification_training
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.8 and later.
  - python=3.9.*
  - pip

  - pip:
      # Base AzureML SDK
      - azureml-sdk

      # Must match AzureML SDK version.
      # https://docs.microsoft.com/en-us/azure/machine-learning/concept-environments
      - azureml-defaults

      # Training deps
      - scikit-learn

      # Scoring deps
      - inference-schema[numpy-support]

      # MLOps with R
      - azure-storage-blob

      # Job lib- whatever I don't know what we use it for
      - joblib
      
      #pandas
      - pandas

      #mlflow for experiment tracking
      - mlflow==2.3.2

      #Pysocks.
      - PySocks

      #Azure ml
      - azureml

      #Ray
      - ray[air]

      #Form_Recognizer
      - azure-ai-formrecognizer

      #azure.ai.ml
      - azure-ai-ml

      #Collections
      - collection==0.1.4

      # Integration of Azureml with mlflow
      - azureml-mlflow